//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bill
    {
         [Key]
        public int BillId { get; set; }
        public System.DateTimeOffset BillDate { get; set; }
        public System.DateTimeOffset BillDueDate { get; set; }
        public string BillName { get; set; }
        public int BillTypeId { get; set; }
        public int GoodsReceivedNoteId { get; set; }
        public string VendorDONumber { get; set; }
        public string VendorInvoiceNumber { get; set; }
    }
}
