//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GoodsReceivedNote
    {
         [Key]
        public int GoodsReceivedNoteId { get; set; }
        public System.DateTimeOffset GRNDate { get; set; }
        public string GoodsReceivedNoteName { get; set; }
        public bool IsFullReceive { get; set; }
        public int PurchaseOrderId { get; set; }
        public string VendorDONumber { get; set; }
        public string VendorInvoiceNumber { get; set; }
        public int WarehouseId { get; set; }
    }
}
