//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentVoucher
    {
        public int PaymentvoucherId { get; set; }
        public int BillId { get; set; }
        public int CashBankId { get; set; }
        public bool IsFullPayment { get; set; }
        public double PaymentAmount { get; set; }
        public System.DateTimeOffset PaymentDate { get; set; }
        public int PaymentTypeId { get; set; }
        public string PaymentVoucherName { get; set; }
    }
}
