//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PaymentReceive
    {
         [Key]
        public int PaymentReceiveId { get; set; }
        public int InvoiceId { get; set; }
        public bool IsFullPayment { get; set; }
        public double PaymentAmount { get; set; }
        public System.DateTimeOffset PaymentDate { get; set; }
        public string PaymentReceiveName { get; set; }
        public int PaymentTypeId { get; set; }
    }
}
