//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [Key]
        public int ProductId { get; set; }
        public string Barcode { get; set; }
        public int BranchId { get; set; }
        public int CurrencyId { get; set; }
        public double DefaultBuyingPrice { get; set; }
        public double DefaultSellingPrice { get; set; }
        public string Description { get; set; }
        public string ProductCode { get; set; }
        public string ProductImageUrl { get; set; }
        public string ProductName { get; set; }
        public int UnitOfMeasureId { get; set; }
    }
}
