//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderLine
    {
        public int PurchaseOrderLineId { get; set; }
        public double Amount { get; set; }
        public string Description { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<double> DiscountPercentage { get; set; }
        public Nullable<double> Price { get; set; }
        public int ProductId { get; set; }
        public int PurchaseOrderId { get; set; }
        public double Quantity { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> TaxAmount { get; set; }
        public Nullable<double> TaxPercentage { get; set; }
        public double Total { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
