//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PurchaseOrderLine
    {
         [Key]
        public int PurchaseOrderLineId { get; set; }
        public double Amount { get; set; }
        public string Description { get; set; }
        public double DiscountAmount { get; set; }
        public double DiscountPercentage { get; set; }
        public double Price { get; set; }
        public int ProductId { get; set; }
        public int PurchaseOrderId { get; set; }
        public double Quantity { get; set; }
        public double SubTotal { get; set; }
        public double TaxAmount { get; set; }
        public double TaxPercentage { get; set; }
        public double Total { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
