//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SalesOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesOrder()
        {
            this.SalesOrderLines = new HashSet<SalesOrderLine>();
        }
         [Key]

        public int SalesOrderId { get; set; }
        public double Amount { get; set; }
        public int BranchId { get; set; }
        public int CurrencyId { get; set; }
        public int CustomerId { get; set; }
        public string CustomerRefNumber { get; set; }
        public System.DateTimeOffset DeliveryDate { get; set; }
        public double Discount { get; set; }
        public double Freight { get; set; }
        public System.DateTimeOffset OrderDate { get; set; }
        public string Remarks { get; set; }
        public string SalesOrderName { get; set; }
        public int SalesTypeId { get; set; }
        public double SubTotal { get; set; }
        public double Tax { get; set; }
        public double Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderLine> SalesOrderLines { get; set; }
    }
}
