//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderLine
    {
        public int SalesOrderLineId { get; set; }
        public double Amount { get; set; }
        public string Description { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<double> DiscountPercentage { get; set; }
        public double Price { get; set; }
        public int ProductId { get; set; }
        public double Quantity { get; set; }
        public int SalesOrderId { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> TaxAmount { get; set; }
        public Nullable<double> TaxPercentage { get; set; }
        public double Total { get; set; }
        public System.DateTime DateUpdate { get; set; }
    
        public virtual SalesOrder SalesOrder { get; set; }
    }
}
