//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int ShipmentId { get; set; }
        public bool IsFullShipment { get; set; }
        public int SalesOrderId { get; set; }
        public System.DateTimeOffset ShipmentDate { get; set; }
        public string ShipmentName { get; set; }
        public int ShipmentTypeId { get; set; }
        public int WarehouseId { get; set; }
    }
}
